In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
dataset = pd.read_csv(r'C:\Projects_ciência_dados\project_credit_risk\data\raw\home-credit-default-risk\credit_card_balance.csv')

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3840312 entries, 0 to 3840311
Data columns (total 23 columns):
 #   Column                      Dtype
---  ------                      -----
 0   SK_ID_PREV                  int64
 1   SK_ID_CURR                  int64
 2   MONTHS_BALANCE              int64
 3   AMT_BALANCE                 float64
 4   AMT_CREDIT_LIMIT_ACTUAL     int64
 5   AMT_DRAWINGS_ATM_CURRENT    float64
 6   AMT_DRAWINGS_CURRENT        float64
 7   AMT_DRAWINGS_OTHER_CURRENT  float64
 8   AMT_DRAWINGS_POS_CURRENT    float64
 9   AMT_INST_MIN_REGULARITY     float64
 10  AMT_PAYMENT_CURRENT         float64
 11  AMT_PAYMENT_TOTAL_CURRENT   float64
 12  AMT_RECEIVABLE_PRINCIPAL    float64
 13  AMT_RECIVABLE               float64
 14  AMT_TOTAL_RECEIVABLE        float64
 15  CNT_DRAWINGS_ATM_CURRENT    float64
 16  CNT_DRAWINGS_CURRENT        int64
 17  CNT_DRAWINGS_OTHER_CURRENT  float64
 18  CNT_DRAWINGS_POS_CURRENT    float64
 19  CNT_INSTALMENT_MATURE_CUM   float64
 20  NAME_CONTRACT_STATUS        object
 21  SK_DPD                      int64
 22  SK_DPD_DEF                  int64
dtypes: float64(15), int64(7), object(1)
memory usage: 673.9+ MB

In [4]:
dataset.shape

(3840312, 23)

In [5]:
dataset.describe()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECEIVABLE_PRINCIPAL,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,SK_DPD,SK_DPD_DEF
count,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.090496e+06,3.840312e+06,3.090496e+06,3.090496e+06,3.535076e+06,...,3.840312e+06,3.840312e+06,3.840312e+06,3.090496e+06,3.840312e+06,3.090496e+06,3.090496e+06,3.535076e+06,3.840312e+06,3.840312e+06
mean,1.904504e+06,2.783242e+05,-3.452192e+01,5.830016e+04,1.538080e+05,5.961325e+03,7.433388e+03,2.881696e+02,2.968805e+03,3.540204e+03,...,5.596588e+04,5.808881e+04,5.809829e+04,3.094490e-01,7.031439e-01,4.812496e-03,5.594791e-01,2.082508e+01,9.283667e+00,3.316220e-01
std,5.364695e+05,1.027045e+05,2.666775e+01,1.063070e+05,1.651457e+05,2.822569e+04,3.384608e+04,8.201989e+03,2.079689e+04,5.600154e+03,...,1.025336e+05,1.059654e+05,1.059718e+05,1.100401e+00,3.190347e+00,8.263861e-02,3.240649e+00,2.005149e+01,9.751570e+01,2.147923e+01
min,1.000018e+06,1.000060e+05,-9.600000e+01,-4.202502e+05,0.000000e+00,-6.827310e+03,-6.211620e+03,0.000000e+00,0.000000e+00,0.000000e+00,...,-4.233058e+05,-4.202502e+05,-4.202502e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.434385e+06,1.895170e+05,-5.500000e+01,0.000000e+00,4.500000e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00
50%,1.897122e+06,2.783960e+05,-2.800000e+01,0.000000e+00,1.125000e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+01,0.000000e+00,0.000000e+00
75%,2.369328e+06,3.675800e+05,-1.100000e+01,8.904669e+04,1.800000e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.633911e+03,...,8.535924e+04,8.889949e+04,8.891451e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.200000e+01,0.000000e+00,0.000000e+00
max,2.843496e+06,4.562500e+05,-1.000000e+00,1.505902e+06,1.350000e+06,2.115000e+06,2.287098e+06,1.529847e+06,2.239274e+06,2.028820e+05,...,1.472317e+06,1.493338e+06,1.493338e+06,5.100000e+01,1.650000e+02,1.200000e+01,1.650000e+02,1.200000e+02,3.260000e+03,3.260000e+03

In [6]:
dataset.columns

Index(['SK_ID_PREV', 'SK_ID_CURR', 'MONTHS_BALANCE', 'AMT_BALANCE',
       'AMT_CREDIT_LIMIT_ACTUAL', 'AMT_DRAWINGS_ATM_CURRENT',
       'AMT_DRAWINGS_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT',
       'AMT_DRAWINGS_POS_CURRENT', 'AMT_INST_MIN_REGULARITY',
       'AMT_PAYMENT_CURRENT', 'AMT_PAYMENT_TOTAL_CURRENT',
       'AMT_RECEIVABLE_PRINCIPAL', 'AMT_RECIVABLE', 'AMT_TOTAL_RECEIVABLE',
       'CNT_DRAWINGS_ATM_CURRENT', 'CNT_DRAWINGS_CURRENT',
       'CNT_DRAWINGS_OTHER_CURRENT', 'CNT_DRAWINGS_POS_CURRENT',
       'CNT_INSTALMENT_MATURE_CUM', 'NAME_CONTRACT_STATUS', 'SK_DPD',
       'SK_DPD_DEF'],
      dtype='object')

Definição de porcentagem de nulos para cada coluna

In [7]:
def porcentagem_nulos_df(df):
    return (
        df.isnull()
          .mean()
          .mul(100)
          .reset_index()
          .rename(columns={'index': 'coluna', 0: 'porcentagem_nulos'})
          .sort_values(by='porcentagem_nulos', ascending=False)
    )

In [8]:
pn = porcentagem_nulos_df(dataset)
pn

                        coluna  porcentagem_nulos
10         AMT_PAYMENT_CURRENT          19.998063
18    CNT_DRAWINGS_POS_CURRENT          19.524872
5     AMT_DRAWINGS_ATM_CURRENT          19.524872
15    CNT_DRAWINGS_ATM_CURRENT          19.524872
8     AMT_DRAWINGS_POS_CURRENT          19.524872
7   AMT_DRAWINGS_OTHER_CURRENT          19.524872
17  CNT_DRAWINGS_OTHER_CURRENT          19.524872
19   CNT_INSTALMENT_MATURE_CUM           7.948208
9      AMT_INST_MIN_REGULARITY           7.948208
6         AMT_DRAWINGS_CURRENT           0.000000
4      AMT_CREDIT_LIMIT_ACTUAL           0.000000
0                   SK_ID_PREV           0.000000
1                   SK_ID_CURR           0.000000
3                  AMT_BALANCE           0.000000
2               MONTHS_BALANCE           0.000000
14        AMT_TOTAL_RECEIVABLE           0.000000
13               AMT_RECIVABLE           0.000000
12    AMT_RECEIVABLE_PRINCIPAL           0.000000
11   AMT_PAYMENT_TOTAL_CURRENT           0.000000
16        CNT_DRAWINGS_CURRENT           0.000000
20        NAME_CONTRACT_STATUS           0.000000
21                      SK_DPD           0.000000
22                  SK_DPD_DEF           0.000000

In [9]:
dataset.isnull().sum()

SK_ID_PREV                         0
SK_ID_CURR                         0
MONTHS_BALANCE                     0
AMT_BALANCE                        0
AMT_CREDIT_LIMIT_ACTUAL            0
AMT_DRAWINGS_ATM_CURRENT      749816
AMT_DRAWINGS_CURRENT               0
AMT_DRAWINGS_OTHER_CURRENT    749816
AMT_DRAWINGS_POS_CURRENT      749816
AMT_INST_MIN_REGULARITY       305236
AMT_PAYMENT_CURRENT           767988
AMT_PAYMENT_TOTAL_CURRENT          0
AMT_RECEIVABLE_PRINCIPAL           0
AMT_RECIVABLE                      0
AMT_TOTAL_RECEIVABLE               0
CNT_DRAWINGS_ATM_CURRENT      749816
CNT_DRAWINGS_CURRENT               0
CNT_DRAWINGS_OTHER_CURRENT    749816
CNT_DRAWINGS_POS_CURRENT      749816
CNT_INSTALMENT_MATURE_CUM     305236
NAME_CONTRACT_STATUS               0
SK_DPD                             0
SK_DPD_DEF                         0
dtype: int64

In [10]:
dataset

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.5,0.0,877.5,1700.325,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.000,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.0,0.0,0.0,2250.000,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.0,0.0,0.0,11795.760,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.0,0.0,11547.0,22924.890,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840307,1036507,328243,-9,0.000,45000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3840308,1714892,347207,-9,0.000,45000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,23.0,Active,0,0
3840309,1302323,215757,-9,275784.975,585000,270000.0,270000.0,0.0,0.0,2250.000,...,273093.975,273093.975,2.0,2,0.0,0.0,18.0,Active,0,0
3840310,1624872,430337,-10,0.000,450000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3840311,2411345,236760,-10,0.000,157500,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,21.0,Completed,0,0

In [11]:
dataset['SK_ID_CURR'].value_counts()

SK_ID_CURR
186401    192
311118    178
120076    140
128827    129
246089    128
         ...
304318      1
359275      1
405801      1
135005      1
438104      1
Name: count, Length: 103558, dtype: int64

Mediana de 22 clientes iguais

In [12]:
dataset.groupby('SK_ID_CURR').size().median()

np.float64(22.0)

- Saldo (limite) máximo para pegar recorrência, bom histórico de pagamento e renda
- Desvio padrão para entender estabilidade dos limites dos cartões
- Mean para entender resumir os saldos dos cartões
- Colocar Last para entender o último saldo do cartão

In [13]:
dataset_agg = dataset.groupby('SK_ID_CURR')['AMT_BALANCE'].agg(
    AMT_BALANCE_BIGGER = 'max',
    AMT_BALANCE_STD = 'std',
    AMT_BALANCE_MEAN = 'mean'
)

In [14]:
last_balance = (
    dataset
    .sort_values(['SK_ID_CURR','MONTHS_BALANCE'])
    .groupby('SK_ID_CURR')
    .tail(1)[['SK_ID_CURR','AMT_BALANCE']]
    .rename(columns={'AMT_BALANCE':'AMT_BALANCE_LAST'})
)

last_balance

         SK_ID_CURR  AMT_BALANCE_LAST
584804       100006             0.000
2739019      100011             0.000
2673656      100013             0.000
1278805      100021             0.000
778090       100023             0.000
...             ...               ...
76410        456244             0.000
2017416      456246            62.685
1148019      456247             0.000
735902       456248             0.000
140639       456250        153832.725

[103558 rows x 2 columns]

In [15]:
dataset_agg

            AMT_BALANCE_BIGGER  AMT_BALANCE_STD  AMT_BALANCE_MEAN
SK_ID_CURR
100006                   0.000         0.000000          0.000000
100011              189000.000     68127.238270      54482.111149
100013              161420.220     43237.406997      18159.919219
100021                   0.000         0.000000          0.000000
100023                   0.000         0.000000          0.000000
...                        ...              ...               ...
456244              453627.675    181540.706436     131834.730732
456246               43490.115     18263.381378      13136.731875
456247              190202.130     56576.242229      23216.396211
456248                   0.000         0.000000          0.000000
456250              200208.915     12914.006678     173589.326250

[103558 rows x 3 columns]

In [16]:
last_balance = last_balance.set_index('SK_ID_CURR')

dataset_agg = dataset_agg.join(last_balance)

In [17]:
dataset_agg

,AMT_BALANCE_BIGGER,AMT_BALANCE_STD,AMT_BALANCE_MEAN,AMT_BALANCE_LAST
SK_ID_CURR,,,,
100006,0.000,0.000000,0.000000,0.000
100011,189000.000,68127.238270,54482.111149,0.000
100013,161420.220,43237.406997,18159.919219,0.000
100021,0.000,0.000000,0.000000,0.000
100023,0.000,0.000000,0.000000,0.000
...,...,...,...,...
456244,453627.675,181540.706436,131834.730732,0.000
456246,43490.115,18263.381378,13136.731875,62.685
456247,190202.130,56576.242229,23216.396211,0.000
456248,0.000,0.000000,0.000000,0.000
456250,200208.915,12914.006678,173589.326250,153832.725

In [18]:
credit_limit = dataset.groupby('SK_ID_CURR')['AMT_CREDIT_LIMIT_ACTUAL'].agg(
    CREDIT_LIMIT_ACTUAL_BIGGER = 'max',
    CREDIT_LIMIT_ACTUAL_MEAN = 'mean',
    CREDIT_LIMIT_ACTUAL_STD = 'std'
)

In [19]:
last_credit_limit = (
    dataset
    .sort_values(['SK_ID_CURR','MONTHS_BALANCE'])
    .groupby('SK_ID_CURR')
    .tail(1)[['SK_ID_CURR','AMT_CREDIT_LIMIT_ACTUAL']]
    .rename(columns={'AMT_CREDIT_LIMIT_ACTUAL':'CREDIT_LIMIT_ACTUAL_LAST'})
)

last_credit_limit

         SK_ID_CURR  CREDIT_LIMIT_ACTUAL_LAST
584804       100006                    270000
2739019      100011                     90000
2673656      100013                     45000
1278805      100021                    675000
778090       100023                    225000
...             ...                       ...
76410        456244                         0
2017416      456246                    135000
1148019      456247                         0
735902       456248                    900000
140639       456250                    175500

[103558 rows x 2 columns]

In [20]:
dataset_agg = dataset_agg.join(credit_limit)
dataset_agg

,AMT_BALANCE_BIGGER,AMT_BALANCE_STD,AMT_BALANCE_MEAN,AMT_BALANCE_LAST,CREDIT_LIMIT_ACTUAL_BIGGER,CREDIT_LIMIT_ACTUAL_MEAN,CREDIT_LIMIT_ACTUAL_STD
SK_ID_CURR,,,,,,,
100006,0.000,0.000000,0.000000,0.000,270000,270000.000000,0.000000
100011,189000.000,68127.238270,54482.111149,0.000,180000,164189.189189,34482.743620
100013,161420.220,43237.406997,18159.919219,0.000,157500,131718.750000,47531.585759
100021,0.000,0.000000,0.000000,0.000,675000,675000.000000,0.000000
100023,0.000,0.000000,0.000000,0.000,225000,135000.000000,96214.047088
...,...,...,...,...,...,...,...
456244,453627.675,181540.706436,131834.730732,0.000,450000,296341.463415,216041.154616
456246,43490.115,18263.381378,13136.731875,62.685,135000,135000.000000,0.000000
456247,190202.130,56576.242229,23216.396211,0.000,180000,144000.000000,72381.965545
456248,0.000,0.000000,0.000000,0.000,900000,900000.000000,0.000000
456250,200208.915,12914.006678,173589.326250,153832.725,180000,178875.000000,2035.201576

In [21]:
last_credit_limit = last_credit_limit.set_index('SK_ID_CURR')

In [22]:
dataset_agg = dataset_agg.join(last_credit_limit)

In [23]:
dataset_agg

,AMT_BALANCE_BIGGER,AMT_BALANCE_STD,AMT_BALANCE_MEAN,AMT_BALANCE_LAST,CREDIT_LIMIT_ACTUAL_BIGGER,CREDIT_LIMIT_ACTUAL_MEAN,CREDIT_LIMIT_ACTUAL_STD,CREDIT_LIMIT_ACTUAL_LAST
SK_ID_CURR,,,,,,,,
100006,0.000,0.000000,0.000000,0.000,270000,270000.000000,0.000000,270000
100011,189000.000,68127.238270,54482.111149,0.000,180000,164189.189189,34482.743620,90000
100013,161420.220,43237.406997,18159.919219,0.000,157500,131718.750000,47531.585759,45000
100021,0.000,0.000000,0.000000,0.000,675000,675000.000000,0.000000,675000
100023,0.000,0.000000,0.000000,0.000,225000,135000.000000,96214.047088,225000
...,...,...,...,...,...,...,...,...
456244,453627.675,181540.706436,131834.730732,0.000,450000,296341.463415,216041.154616,0
456246,43490.115,18263.381378,13136.731875,62.685,135000,135000.000000,0.000000,135000
456247,190202.130,56576.242229,23216.396211,0.000,180000,144000.000000,72381.965545,0
456248,0.000,0.000000,0.000000,0.000,900000,900000.000000,0.000000,900000
456250,200208.915,12914.006678,173589.326250,153832.725,180000,178875.000000,2035.201576,175500

Normalmente, o maior limite do cartão é o último. Nesse caso, essa suposição esta correta

In [24]:
dataset_agg.loc[dataset_agg['CREDIT_LIMIT_ACTUAL_BIGGER'] == dataset_agg['CREDIT_LIMIT_ACTUAL_LAST']].shape[0]

61604

#### AMT_DRAWINGS_ATM_CURRENT

- max é o valor máximo que o indivíduo sacou no mês. Ajuda a entender extremo
- std é o desvio padrão dos saques. Ajuda a entender constância
- mean é a média dos valores dos saques. Ajuda a sumarizar os valores das operações
- median é a mediana dos saques e é importante para fazer uma análise desconsiderando os outliers
- count é a quantidade de saques que foram feitos

In [25]:
DRAWINGS_ATM_CURRENT = dataset.groupby('SK_ID_CURR')['AMT_DRAWINGS_ATM_CURRENT'].agg(
    DRAWINGS_ATM_CURRENT_BIGGER = 'max',
    DRAWINGS_ATM_CURRENT_STD = 'std',
    DRAWINGS_ATM_CURRENT_MEAN = 'mean',
    DRAWINGS_ATM_CURRENT_MEDIAN = 'median',
    DRAWINGS_ATM_CURRENT_COUNT = 'count',
    DRAWINGS_ATM_CURRENT_SUM = 'sum'
)

dataset_agg = dataset_agg.join(DRAWINGS_ATM_CURRENT)
dataset_agg

,AMT_BALANCE_BIGGER,AMT_BALANCE_STD,AMT_BALANCE_MEAN,AMT_BALANCE_LAST,CREDIT_LIMIT_ACTUAL_BIGGER,CREDIT_LIMIT_ACTUAL_MEAN,CREDIT_LIMIT_ACTUAL_STD,CREDIT_LIMIT_ACTUAL_LAST,DRAWINGS_ATM_CURRENT_BIGGER,DRAWINGS_ATM_CURRENT_STD,DRAWINGS_ATM_CURRENT_MEAN,DRAWINGS_ATM_CURRENT_MEDIAN,DRAWINGS_ATM_CURRENT_COUNT,DRAWINGS_ATM_CURRENT_SUM
SK_ID_CURR,,,,,,,,,,,,,,
100006,0.000,0.000000,0.000000,0.000,270000,270000.000000,0.000000,270000,NaN,NaN,NaN,NaN,0,0.0
100011,189000.000,68127.238270,54482.111149,0.000,180000,164189.189189,34482.743620,90000,180000.0,20924.574974,2432.432432,0.0,74,180000.0
100013,161420.220,43237.406997,18159.919219,0.000,157500,131718.750000,47531.585759,45000,157500.0,28722.270457,6350.000000,0.0,90,571500.0
100021,0.000,0.000000,0.000000,0.000,675000,675000.000000,0.000000,675000,NaN,NaN,NaN,NaN,0,0.0
100023,0.000,0.000000,0.000000,0.000,225000,135000.000000,96214.047088,225000,NaN,NaN,NaN,NaN,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456244,453627.675,181540.706436,131834.730732,0.000,450000,296341.463415,216041.154616,0,279000.0,54198.747820,24475.609756,0.0,41,1003500.0
456246,43490.115,18263.381378,13136.731875,62.685,135000,135000.000000,0.000000,135000,0.0,0.000000,0.000000,0.0,8,0.0
456247,190202.130,56576.242229,23216.396211,0.000,180000,144000.000000,72381.965545,0,96750.0,13508.768709,2136.315789,0.0,95,202950.0
456248,0.000,0.000000,0.000000,0.000,900000,900000.000000,0.000000,900000,NaN,NaN,NaN,NaN,0,0.0
456250,200208.915,12914.006678,173589.326250,153832.725,180000,178875.000000,2035.201576,175500,171000.0,49195.343460,15000.000000,0.0,12,180000.0

Grande parte da mediana é zero

In [26]:
dataset_agg.loc[dataset_agg['DRAWINGS_ATM_CURRENT_MEDIAN'] == 0].shape[0]

61890

#### AMT_DRAWINGS_CURRENT

fazer rate depois

In [27]:
DRAWINGS_CURRENT = dataset.groupby('SK_ID_CURR')['AMT_DRAWINGS_CURRENT'].agg(
    DRAWINGS_CURRENT_BIGGER = 'max',
    DRAWINGS_CURRENT_STD = 'std',
    DRAWINGS_CURRENT_MEAN = 'mean',
    DRAWINGS_CURRENT_MEDIAN = 'median',
    DRAWINGS_CURRENT_SUM = 'sum'
)

dataset_agg = dataset_agg.join(DRAWINGS_CURRENT)

In [28]:
dataset_agg

,AMT_BALANCE_BIGGER,AMT_BALANCE_STD,AMT_BALANCE_MEAN,AMT_BALANCE_LAST,CREDIT_LIMIT_ACTUAL_BIGGER,CREDIT_LIMIT_ACTUAL_MEAN,CREDIT_LIMIT_ACTUAL_STD,CREDIT_LIMIT_ACTUAL_LAST,DRAWINGS_ATM_CURRENT_BIGGER,DRAWINGS_ATM_CURRENT_STD,DRAWINGS_ATM_CURRENT_MEAN,DRAWINGS_ATM_CURRENT_MEDIAN,DRAWINGS_ATM_CURRENT_COUNT,DRAWINGS_ATM_CURRENT_SUM,DRAWINGS_CURRENT_BIGGER,DRAWINGS_CURRENT_STD,DRAWINGS_CURRENT_MEAN,DRAWINGS_CURRENT_MEDIAN,DRAWINGS_CURRENT_SUM
SK_ID_CURR,,,,,,,,,,,,,,,,,,,
100006,0.000,0.000000,0.000000,0.000,270000,270000.000000,0.000000,270000,NaN,NaN,NaN,NaN,0,0.0,0.00,0.000000,0.000000,0.000,0.000
100011,189000.000,68127.238270,54482.111149,0.000,180000,164189.189189,34482.743620,90000,180000.0,20924.574974,2432.432432,0.0,74,180000.0,180000.00,20924.574974,2432.432432,0.000,180000.000
100013,161420.220,43237.406997,18159.919219,0.000,157500,131718.750000,47531.585759,45000,157500.0,28722.270457,6350.000000,0.0,90,571500.0,157500.00,27843.366225,5953.125000,0.000,571500.000
100021,0.000,0.000000,0.000000,0.000,675000,675000.000000,0.000000,675000,NaN,NaN,NaN,NaN,0,0.0,0.00,0.000000,0.000000,0.000,0.000
100023,0.000,0.000000,0.000000,0.000,225000,135000.000000,96214.047088,225000,NaN,NaN,NaN,NaN,0,0.0,0.00,0.000000,0.000000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456244,453627.675,181540.706436,131834.730732,0.000,450000,296341.463415,216041.154616,0,279000.0,54198.747820,24475.609756,0.0,41,1003500.0,307953.45,58950.161279,26842.388049,0.000,1100537.910
456246,43490.115,18263.381378,13136.731875,62.685,135000,135000.000000,0.000000,135000,0.0,0.000000,0.000000,0.0,8,0.0,48929.85,21710.636111,15199.256250,526.275,121594.050
456247,190202.130,56576.242229,23216.396211,0.000,180000,144000.000000,72381.965545,0,96750.0,13508.768709,2136.315789,0.0,95,202950.0,96750.00,13507.272226,2149.506474,0.000,204203.115
456248,0.000,0.000000,0.000000,0.000,900000,900000.000000,0.000000,900000,NaN,NaN,NaN,NaN,0,0.0,0.00,0.000000,0.000000,0.000,0.000
456250,200208.915,12914.006678,173589.326250,153832.725,180000,178875.000000,2035.201576,175500,171000.0,49195.343460,15000.000000,0.0,12,180000.0,171000.00,49195.343460,15000.000000,0.000,180000.000

#### AMT_DRAWINGS_OTHER_CURRENT

In [29]:
dataset.loc[dataset['AMT_DRAWINGS_OTHER_CURRENT'] == 0].shape[0]

3078163

In [30]:
dataset.shape

(3840312, 23)

In [31]:
(3078163/3840312) * 100

80.15398228060637

In [32]:
DRAWINGS_OTHER_CURRENT = dataset.groupby('SK_ID_CURR')['AMT_DRAWINGS_OTHER_CURRENT'].agg(
    DRAWINGS_OTHER_CURRENT_SUM = 'sum' 
)

dataset_agg = dataset_agg.join(DRAWINGS_OTHER_CURRENT)

In [33]:
DRAWINGS_OTHER_CURRENT.loc[DRAWINGS_OTHER_CURRENT['DRAWINGS_OTHER_CURRENT_SUM'] == 0].shape[0]

97057

In [34]:
DRAWINGS_OTHER_CURRENT.shape

(103558, 1)

93.72% das amostras são zero, provavelmente precisará ser excluída depois

In [35]:
(97057/103558)*100

93.72235848510013

#### AMT_DRAWINGS_POS_CURRENT

In [36]:
DRAWINGS_POS_CURRENT = dataset.groupby('SK_ID_CURR')['AMT_DRAWINGS_POS_CURRENT'].agg(
    DRAWINGS_POS_CURRENT_BIGGER = 'max',
    DRAWINGS_POS_CURRENT_STD = 'std',
    DRAWINGS_POS_CURRENT_MEAN = 'mean',
    DRAWINGS_POS_CURRENT_MEDIAN = 'median',
    DRAWINGS_POS_CURRENT_SUM = 'sum'
)

dataset_agg = dataset_agg.join(DRAWINGS_POS_CURRENT)

In [37]:
dataset_agg

,AMT_BALANCE_BIGGER,AMT_BALANCE_STD,AMT_BALANCE_MEAN,AMT_BALANCE_LAST,CREDIT_LIMIT_ACTUAL_BIGGER,CREDIT_LIMIT_ACTUAL_MEAN,CREDIT_LIMIT_ACTUAL_STD,CREDIT_LIMIT_ACTUAL_LAST,DRAWINGS_ATM_CURRENT_BIGGER,DRAWINGS_ATM_CURRENT_STD,...,DRAWINGS_CURRENT_STD,DRAWINGS_CURRENT_MEAN,DRAWINGS_CURRENT_MEDIAN,DRAWINGS_CURRENT_SUM,DRAWINGS_OTHER_CURRENT_SUM,DRAWINGS_POS_CURRENT_BIGGER,DRAWINGS_POS_CURRENT_STD,DRAWINGS_POS_CURRENT_MEAN,DRAWINGS_POS_CURRENT_MEDIAN,DRAWINGS_POS_CURRENT_SUM
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100006,0.000,0.000000,0.000000,0.000,270000,270000.000000,0.000000,270000,NaN,NaN,...,0.000000,0.000000,0.000,0.000,0.0,NaN,NaN,NaN,NaN,0.000
100011,189000.000,68127.238270,54482.111149,0.000,180000,164189.189189,34482.743620,90000,180000.0,20924.574974,...,20924.574974,2432.432432,0.000,180000.000,0.0,0.000,0.000000,0.000000,0.000,0.000
100013,161420.220,43237.406997,18159.919219,0.000,157500,131718.750000,47531.585759,45000,157500.0,28722.270457,...,27843.366225,5953.125000,0.000,571500.000,0.0,0.000,0.000000,0.000000,0.000,0.000
100021,0.000,0.000000,0.000000,0.000,675000,675000.000000,0.000000,675000,NaN,NaN,...,0.000000,0.000000,0.000,0.000,0.0,NaN,NaN,NaN,NaN,0.000
100023,0.000,0.000000,0.000000,0.000,225000,135000.000000,96214.047088,225000,NaN,NaN,...,0.000000,0.000000,0.000,0.000,0.0,NaN,NaN,NaN,NaN,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456244,453627.675,181540.706436,131834.730732,0.000,450000,296341.463415,216041.154616,0,279000.0,54198.747820,...,58950.161279,26842.388049,0.000,1100537.910,0.0,30911.850,7177.457716,2363.015854,0.000,96883.650
456246,43490.115,18263.381378,13136.731875,62.685,135000,135000.000000,0.000000,135000,0.0,0.000000,...,21710.636111,15199.256250,526.275,121594.050,0.0,48929.850,21710.636111,15199.256250,526.275,121594.050
456247,190202.130,56576.242229,23216.396211,0.000,180000,144000.000000,72381.965545,0,96750.0,13508.768709,...,13507.272226,2149.506474,0.000,204203.115,0.0,1253.115,128.566886,13.190684,0.000,1253.115
456248,0.000,0.000000,0.000000,0.000,900000,900000.000000,0.000000,900000,NaN,NaN,...,0.000000,0.000000,0.000,0.000,0.0,NaN,NaN,NaN,NaN,0.000
456250,200208.915,12914.006678,173589.326250,153832.725,180000,178875.000000,2035.201576,175500,171000.0,49195.343460,...,49195.343460,15000.000000,0.000,180000.000,0.0,0.000,0.000000,0.000000,0.000,0.000

#### AMT_INST_MIN_REGULARITY

In [38]:
AMT_INST_MIN_REGULARITY = dataset.groupby('SK_ID_CURR')['AMT_INST_MIN_REGULARITY'].agg(
    INST_MIN_REGULARITY_MEAN = 'mean',
    INST_MIN_REGULARITY_MEDIAN = 'median'
)

dataset_agg = dataset_agg.join(AMT_INST_MIN_REGULARITY)

#### AMT_PAYMENT_CURRENT

In [39]:
AMT_PAYMENT_CURRENT = dataset.groupby('SK_ID_CURR')['AMT_PAYMENT_CURRENT'].agg(
    PAYMENT_CURRENT_MEAN = 'mean',
    PAYMENT_CURRENT_MEDIAN = 'median',
    PAYMENT_CURRENT_MAX = 'max',
    PAYMENT_CURRENT_STD = 'std'
)

dataset_agg = dataset_agg.join(AMT_PAYMENT_CURRENT)

#### AMT_PAYMENT_TOTAL_CURRENT

In [40]:
AMT_PAYMENT_TOTAL_CURRENT = dataset.groupby('SK_ID_CURR')['AMT_PAYMENT_TOTAL_CURRENT'].agg(
     PAYMENT_TOTAL_CURRENT_MAX = 'max',
     PAYMENT_TOTAL_CURRENT_MEDIAN = 'median',
     PAYMENT_TOTAL_CURRENT_MEAN = 'mean',
     PAYMENT_TOTAL_CURRENT_STD = 'std'
)

dataset_agg = dataset_agg.join(AMT_PAYMENT_TOTAL_CURRENT)

Coeficiente de variação: mede se o pagamento do cliente é variável ou instável

In [41]:
dataset_agg['PAYMENT_TOTAL_CURRENT_CV'] = (
    dataset_agg['PAYMENT_TOTAL_CURRENT_STD'] / dataset_agg['PAYMENT_TOTAL_CURRENT_MEAN']
)

Máximo sobre mediana: Indica se os pagamentos são consistente ou não. Se essa métrica for alta, indica que o cliente é insconsistente pra cima. Se for próximo de 1, indica que é consistente

In [42]:
dataset_agg['PAYMENT_MEDIAN_MAX_RATIO'] = (
    dataset_agg['PAYMENT_TOTAL_CURRENT_MAX'] / dataset_agg['PAYMENT_TOTAL_CURRENT_MEDIAN']
)

Subtração mean e median: pega outliers e consistência no pagamento

In [43]:
dataset_agg['PAYMENT_TOTAL_MEAN_MEDIAN_DIFF'] = (
    dataset_agg['PAYMENT_TOTAL_CURRENT_MEAN'] /
    dataset_agg['PAYMENT_TOTAL_CURRENT_MEDIAN']
)

Pagamento sobre dívida: se for alto, indica que o cliente paga. Se for baixo, indica que o cliente acumula dívida

In [44]:
dataset_agg['PAYMENT_TO_BALANCE_RATIO'] = (
    dataset_agg['PAYMENT_TOTAL_CURRENT_MEAN'] / dataset_agg['AMT_BALANCE_MEAN']
)

AMT_RECEIVABLE_PRINCIPAL

In [45]:
AMT_RECEIVABLE_PRINCIPAL = dataset.groupby('SK_ID_CURR')['AMT_RECEIVABLE_PRINCIPAL'].agg(
    RECEIVABLE_PRINCIPAL_MEAN = 'mean',
    RECEIVABLE_PRINCIPAL_MEDIAN = 'median',
    RECEIVABLE_PRINCIPAL_MAX = 'max',
    RECEIVABLE_PRINCIPAL_MIN = 'min',
    RECEIVABLE_PRINCIPAL_STD = 'std'
)

In [46]:
dataset_agg = dataset_agg.join(AMT_RECEIVABLE_PRINCIPAL)

AMT_RECIVABLE

In [49]:
AMT_RECIVABLE = dataset.groupby('SK_ID_CURR')['AMT_RECIVABLE'].agg(
    RECIVABLE_MEAN = 'mean',
    RECIVABLE_MAX = 'max',
    RECIVABLE_STD = 'std'
)

In [50]:
dataset_agg = dataset_agg.join(AMT_RECIVABLE)

In [51]:
AMT_TOTAL_RECEIVABLE = dataset.groupby('SK_ID_CURR')['AMT_RECIVABLE'].agg(
    TOTAL_RECEIVABLE_MEAN = 'mean',
    TOTAL_RECEIVABLE_MAX = 'max',
    TOTAL_RECEIVABLE_MIN  = 'min',
    TOTAL_RECEIVABLE_MEDIAN = 'median',
    TOTAL_RECEIVABLE_STD = 'std'
)

In [52]:
dataset_agg = dataset_agg.join(AMT_TOTAL_RECEIVABLE)

In [53]:
dataset_agg

,AMT_BALANCE_BIGGER,AMT_BALANCE_STD,AMT_BALANCE_MEAN,AMT_BALANCE_LAST,CREDIT_LIMIT_ACTUAL_BIGGER,CREDIT_LIMIT_ACTUAL_MEAN,CREDIT_LIMIT_ACTUAL_STD,CREDIT_LIMIT_ACTUAL_LAST,DRAWINGS_ATM_CURRENT_BIGGER,DRAWINGS_ATM_CURRENT_STD,...,RECEIVABLE_PRINCIPAL_MIN,RECEIVABLE_PRINCIPAL_STD,RECIVABLE_MEAN,RECIVABLE_MAX,RECIVABLE_STD,TOTAL_RECEIVABLE_MEAN,TOTAL_RECEIVABLE_MAX,TOTAL_RECEIVABLE_MIN,TOTAL_RECEIVABLE_MEDIAN,TOTAL_RECEIVABLE_STD
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100006,0.000,0.000000,0.000000,0.000,270000,270000.000000,0.000000,270000,NaN,NaN,...,0.00,0.000000,0.000000,0.000,0.000000,0.000000,0.000,0.000,0.000,0.000000
100011,189000.000,68127.238270,54482.111149,0.000,180000,164189.189189,34482.743620,90000,180000.0,20924.574974,...,0.00,65758.823328,54433.179122,189000.000,68166.970922,54433.179122,189000.000,-563.355,0.000,68166.970922
100013,161420.220,43237.406997,18159.919219,0.000,157500,131718.750000,47531.585759,45000,157500.0,28722.270457,...,0.00,41279.745434,18101.079844,161420.220,43262.026330,18101.079844,161420.220,-274.320,0.000,43262.026330
100021,0.000,0.000000,0.000000,0.000,675000,675000.000000,0.000000,675000,NaN,NaN,...,0.00,0.000000,0.000000,0.000,0.000000,0.000000,0.000,0.000,0.000,0.000000
100023,0.000,0.000000,0.000000,0.000,225000,135000.000000,96214.047088,225000,NaN,NaN,...,0.00,0.000000,0.000000,0.000,0.000000,0.000000,0.000,0.000,0.000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456244,453627.675,181540.706436,131834.730732,0.000,450000,296341.463415,216041.154616,0,279000.0,54198.747820,...,0.00,176058.396403,130767.060732,453627.675,180546.703695,130767.060732,453627.675,0.000,0.000,180546.703695
456246,43490.115,18263.381378,13136.731875,62.685,135000,135000.000000,0.000000,135000,0.0,0.000000,...,0.00,17998.915570,12897.894375,43490.115,18021.227861,12897.894375,43490.115,0.000,753.165,18021.227861
456247,190202.130,56576.242229,23216.396211,0.000,180000,144000.000000,72381.965545,0,96750.0,13508.768709,...,0.00,54103.235131,23128.243105,190202.130,56612.512602,23128.243105,190202.130,-520.605,0.000,56612.512602
456248,0.000,0.000000,0.000000,0.000,900000,900000.000000,0.000000,900000,NaN,NaN,...,0.00,0.000000,0.000000,0.000,0.000000,0.000000,0.000,0.000,0.000,0.000000
456250,200208.915,12914.006678,173589.326250,153832.725,180000,178875.000000,2035.201576,175500,171000.0,49195.343460,...,151808.22,8877.776501,172237.526250,196581.915,11836.134375,172237.526250,196581.915,153832.725,171471.510,11836.134375

Identifica juros. Se o valor for alto, indica muitos juros em relação a dívida

In [54]:
dataset_agg['AMT_RECEIVABLE_FEES'] = dataset_agg['RECIVABLE_MEAN'] / (dataset_agg['RECEIVABLE_PRINCIPAL_MEAN'] + 1)

Identificação de instabilidade. Se for alto, indicando instabilidade em relação as dívidas

In [55]:
dataset_agg['AMT_RECEIVABLE_CV'] = dataset_agg['RECEIVABLE_PRINCIPAL_STD'] / (dataset_agg['RECEIVABLE_PRINCIPAL_MEAN'] + 1)

Mede dívida em relação ao limite. Se baixo, dívida controlada. Se alto, cliente pressionado

In [ ]:
dataset_agg['TOTAL_RECEIVABLE_TO_LIMIT'] = (
    dataset_agg['TOTAL_RECEIVABLE_MEAN'] /
    (dataset_agg['CREDIT_LIMIT_ACTUAL_MEAN'] + 1))

#### CNT_DRAWINGS_ATM_CURRENT

In [61]:
CNT_DRAWINGS_ATM_CURRENT = dataset.groupby('SK_ID_CURR')['CNT_DRAWINGS_ATM_CURRENT'].agg(
    CNT_DRAWINGS_ATM_CURRENT_MEAN = 'mean',
    CNT_DRAWINGS_ATM_CURRENT_MAX = 'max',
    CNT_DRAWINGS_ATM_CURRENT_STD = 'std',
    CNT_DRAWINGS_ATM_CURRENT_MIN = 'min'
)

In [62]:
dataset_agg = dataset_agg.join(CNT_DRAWINGS_ATM_CURRENT)

#### CNT_DRAWINGS_CURRENT

In [63]:
CNT_DRAWINGS_CURRENT = dataset.groupby('SK_ID_CURR')['CNT_DRAWINGS_CURRENT'].agg(
    CNT_DRAWINGS_CURRENT_MEAN = 'mean',
    CNT_DRAWINGS_CURRENT_MAX = 'max',
    CNT_DRAWINGS_CURRENT_MIN = 'min',
    CNT_DRAWINGS_CURRENT_STD = 'std' 
)

In [64]:
dataset_agg = dataset_agg.join(CNT_DRAWINGS_CURRENT)

In [66]:
CNT_DRAWINGS_OTHER_CURRENT = dataset.groupby('SK_ID_CURR')['CNT_DRAWINGS_OTHER_CURRENT'].agg(
    CNT_DRAWINGS_OTHER_CURRENT_MEAN = 'mean',
    CNT_DRAWINGS_OTHER_CURRENT_MAX = 'max',
    CNT_DRAWINGS_OTHER_CURRENT_MIN = 'min',
    CNT_DRAWINGS_OTHER_CURRENT_STD = 'std'
)

In [68]:
dataset_agg = dataset_agg.join(CNT_DRAWINGS_OTHER_CURRENT)

#### CNT_DRAWINGS_POS_CURRENT

In [70]:
CNT_DRAWINGS_POS_CURRENT = dataset.groupby('SK_ID_CURR')['CNT_DRAWINGS_POS_CURRENT'].agg(
    CNT_DRAWINGS_POS_CURRENT_MEAN = 'mean',
    CNT_DRAWINGS_POS_CURRENT_MAX = 'max',
    CNT_DRAWINGS_POS_CURRENT_MIN = 'min',
    CNT_DRAWINGS_POS_CURRENT_STD = 'std'
)

In [71]:
dataset_agg = dataset_agg.join(CNT_DRAWINGS_POS_CURRENT)

Valor sacado / quantidade . Se for alta, significa que o indivíduo pegou muito dinheiro em poucos saques

In [72]:
dataset_agg['DRAWINGS_ATM_CURRENT_AMT_CNT'] = (
    dataset_agg['DRAWINGS_CURRENT_MEAN'] / 
    (dataset_agg['CNT_DRAWINGS_ATM_CURRENT_MEAN'] + 1)
)

Valor gasto em maquininhas / número de compras em maquininhas

In [75]:
dataset_agg['DRAWINGS_ATM_POS_CURRENT_AMT_CNT'] = (
    dataset_agg['DRAWINGS_POS_CURRENT_MEAN'] / 
    (dataset_agg['CNT_DRAWINGS_POS_CURRENT_MEAN'] + 1)
)

Indicar a instabilidade em relação aos saques totais no mês

In [76]:
dataset_agg['CNT_DRAWINGS_CURRENT_CV'] = (
    dataset_agg['CNT_DRAWINGS_CURRENT_STD'] /
    (dataset_agg['CNT_DRAWINGS_CURRENT_MEAN'] + 1)
)

Cliente prefere sacar dinheiro ou usar o cartão?

In [77]:
dataset_agg['ATM_TO_POS_RATIO'] = (
    dataset_agg['CNT_DRAWINGS_ATM_CURRENT_MEAN'] /
    (dataset_agg['CNT_DRAWINGS_POS_CURRENT_MEAN'] + 1)
)

Frequência de uso do cartão

In [78]:
dataset_agg['DRAWINGS_FREQUENCY'] = (
    dataset_agg['CNT_DRAWINGS_CURRENT_MEAN'] /
    12
)

Se alto, muitas compras pequenas. Se baixo, poucas compras grandes

In [79]:
dataset_agg['POS_FRAGMENTATION'] = (
    dataset_agg['CNT_DRAWINGS_POS_CURRENT_MEAN'] /
    (dataset_agg['DRAWINGS_POS_CURRENT_MEAN'] + 1)
)